name: P6
channels:
 - conda-forge                      # priority channel for up-to-date, cross-compiled packages (biopython, selenium, and other packages we might need)
 - defaults                         # fallback to packages from default channel

dependencies:
  - python>=3.10
  - pip

  # Pip‐only dependencies — must be indented under 'pip:' (no leading dash)
  - pip:
      - -r requirements.txt
      - -r requirements_test.txt