name: Setup/Cache Env
description: 'Sets up and caches a python env. Will only install dependencies if no cache was hit.'

runs:
    using: composite
    steps:
        -   name: Set up Python 3.13
            uses: actions/setup-python@v5.6.0
            with:
                python-version: "3.13"

        -   name: Cache Env
            uses: actions/cache@v4.2.3
            id: env-cache
            with:
                path: ${{ env.pythonLocation }}
                key: ${{ hashFiles('./requirements/requirements.txt') }}-${{ hashFiles('./requirements/requirements_scripts.txt') }}-${{ hashFiles('./requirements/requirements_test.txt') }} }}

        -   name: Install Dependencies
            if: ${{ steps.env-cache.outputs.cache-hit != 'true' }}
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements/requirements.txt
                pip install -r requirements/requirements_scripts.txt
                pip install -r requirements/requirements_test.txt
            shell: bash